- Name: service
  ProjectName: gcgtest
  Database: mysql
  Username: root
  Password: ""
  Host: localhost
  Port: 3306
  Table: "company_info,ebook"
  ServicePort: 9091
  ESHost: http://192.168.1.160:9200/
